name: github pages

on: pull_request

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all }}
      ts: ${{ steps.changes.outputs.tf }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          git fetch --no-tags --progress --no-recurse-submodules --depth=1 origin ${{ github.event.pull_request.base.sha }}
          git fetch --no-tags --progress --no-recurse-submodules --depth=1 origin ${{ github.event.pull_request.head.sha }}
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | xargs)"
          echo "::set-output name=tf::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep .tf | xargs)"
      - name: output
        run: |
          echo "${{ steps.changes.outputs.all }}"
          echo "${{ steps.changes.outputs.tf }}"
  lint:
    runs-on: ubuntu-latest
    needs: changedfiles
    # only run there are changed files
    if: ${{needs.changedfiles.outputs.tf}}
    steps:
      - name: echo changed files
        run: echo ${{needs.changedfiles.outputs.tf}}
